spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_hr_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  docker:
    compose:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    defaultModelsExpandDepth: -1
    show-extensions: true
    show-common-extensions: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false
  cache:
    disabled: true

server:
  port: 8585